"""add sent_emails table

Revision ID: 078973083e5b
Revises: 6d068cc054dd
Create Date: 2025-10-23 20:15:37.396218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078973083e5b'
down_revision = '6d068cc054dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_emails')
    # ### end Alembic commands ###
