"""update sent_emails table

Revision ID: 989b1416552e
Revises: 078973083e5b
Create Date: 2025-10-23 20:49:08.987525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b1416552e'
down_revision = '078973083e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('recipients', sa.String(length=255), nullable=True))
        batch_op.drop_column('recipient')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sent_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('recipients')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
